dbt_transformation:
  outputs:
    dev:
      dataset: transformed_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\USER\Downloads\big-star-collectibles-426911-2d73660f99b8.json
      location: US
      method: service-account
      priority: interactive
      project: big-star-collectibles-426911
      threads: 1
      type: bigquery
  target: dev